spring:
  application:
    name: post-service

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "rabbitmq"
    password: "rabbitmq"
    listener:
      simple:
        default-requeue-rejected: false
        prefetch: 2
        retry:
          enabled: true
          initial-interval: 10s
          max-interval: 20s
          multiplier: 2
          max-retries: 3

  jpa:
    open-in-view: false
